apiVersion: v1
kind: Pod
metadata:
 name: prueba-pod
 labels:
  app: pruebaapp
spec:
 containers:
  -name: microservicio01
   image: stevenalvarado/microservicio01
   ports: 
    -containerPort: 8181
  -name: microservicio012
   image: stevenalvarado/microservicio02
   ports: 
    -containerPort: 8282
   
   